import { test, expect } from '@playwright/test';
const chart = Buffer.from(JSON.stringify({ Notes: [{ Uid: 1, just: '1', Flags: 80, holds: [] }], Bpms: [] }));
test('元数据自动匹配、手动覆盖、恢复和换谱清理', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('tab', { name: '显示与特效' }).click();
  await expect(page.locator('#fever-status')).toHaveText('未配置 Fever');
  await page.locator('#chart-file').setInputFiles({ name: 'rhythmgame_chart_103119_04.json', mimeType: 'application/json', buffer: chart });
  await expect(page.locator('#opt-fever-start')).toHaveValue('51.329');
  await expect(page.locator('#opt-fever-end')).toHaveValue('95.723');
  await page.locator('#opt-fever-start').fill('0');
  await page.locator('#opt-fever-end').fill('120');
  await expect(page.locator('#fever-status')).toContainText('手动指定');
  await expect(page.locator('#timeline')).toHaveAttribute('max', '120');
  await page.locator('#opt-fever-end').fill('0');
  await expect(page.locator('#opt-fever-end')).toHaveAttribute('aria-invalid', 'true');
  await expect(page.locator('#fever-status')).toContainText('已停用');
  await page.locator('#fever-reset').click();
  await expect(page.locator('#opt-fever-start')).toHaveValue('51.329');
  await page.locator('#chart-file').setInputFiles({ name: 'custom.json', mimeType: 'application/json', buffer: chart });
  await expect(page.locator('#opt-fever-start')).toHaveValue('');
  await expect(page.locator('#opt-fever-end')).toHaveValue('');
  await expect(page.locator('#fever-status')).toHaveText('未配置 Fever');
  await page.locator('#opt-fever-start').fill('0');
  await page.locator('#opt-fever-end').fill('2');
  await page.locator('#chart-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{') });
  await expect(page.locator('#message')).toContainText('原谱面已保留');
  await expect(page.locator('#opt-fever-end')).toHaveValue('2');
  await page.locator('#demo').click();
  await expect(page.locator('#fever-status')).toHaveText('未配置 Fever');
});
